name: Deploy Helpdesk API to AWS EC2

on:
  push:
    branches:
      - main # Altere para 'master' se sua branch principal tiver esse nome

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Executar Deploy na EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/helpdesk_simples
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart helpdesk